// This file is generated by exql. DO NOT edit.
package model

import "github.com/volatiletech/null"
import "time"

type Fields struct {
	TinyintField                   int          `exql:"column:tinyint_field" json:"tinyint_field"`
	TinyintUnsignedField           uint         `exql:"column:tinyint_unsigned_field" json:"tinyint_unsigned_field"`
	TinyintNullableField           null.Int     `exql:"column:tinyint_nullable_field" json:"tinyint_nullable_field"`
	TinyintUnsignedNullableField   null.Uint    `exql:"column:tinyint_unsigned_nullable_field" json:"tinyint_unsigned_nullable_field"`
	SmallintField                  int          `exql:"column:smallint_field" json:"smallint_field"`
	SmallintUnsignedField          uint         `exql:"column:smallint_unsigned_field" json:"smallint_unsigned_field"`
	SmallintNullableField          null.Int     `exql:"column:smallint_nullable_field" json:"smallint_nullable_field"`
	SmallintUnsignedNullableField  null.Uint    `exql:"column:smallint_unsigned_nullable_field" json:"smallint_unsigned_nullable_field"`
	MediumintField                 int          `exql:"column:mediumint_field" json:"mediumint_field"`
	MediumintUnsignedField         uint         `exql:"column:mediumint_unsigned_field" json:"mediumint_unsigned_field"`
	MediumintNullableField         null.Int     `exql:"column:mediumint_nullable_field" json:"mediumint_nullable_field"`
	MediumintUnsignedNullableField null.Uint    `exql:"column:mediumint_unsigned_nullable_field" json:"mediumint_unsigned_nullable_field"`
	IntField                       int          `exql:"column:int_field" json:"int_field"`
	IntUnsignedField               uint         `exql:"column:int_unsigned_field" json:"int_unsigned_field"`
	IntNullableField               null.Int     `exql:"column:int_nullable_field" json:"int_nullable_field"`
	IntUnsignedNullableField       null.Uint    `exql:"column:int_unsigned_nullable_field" json:"int_unsigned_nullable_field"`
	BigintField                    int64        `exql:"column:bigint_field" json:"bigint_field"`
	BigintUnsignedField            uint64       `exql:"column:bigint_unsigned_field" json:"bigint_unsigned_field"`
	BigintNullableField            null.Int64   `exql:"column:bigint_nullable_field" json:"bigint_nullable_field"`
	BigintUnsignedNullableField    null.Uint64  `exql:"column:bigint_unsigned_nullable_field" json:"bigint_unsigned_nullable_field"`
	FloatField                     float32      `exql:"column:float_field" json:"float_field"`
	FloatNullField                 null.Float32 `exql:"column:float_null_field" json:"float_null_field"`
	DoubleField                    float64      `exql:"column:double_field" json:"double_field"`
	DoubleNullField                null.Float64 `exql:"column:double_null_field" json:"double_null_field"`
	TinytextField                  string       `exql:"column:tinytext_field" json:"tinytext_field"`
	TinytextNullField              null.String  `exql:"column:tinytext_null_field" json:"tinytext_null_field"`
	MediumtextField                string       `exql:"column:mediumtext_field" json:"mediumtext_field"`
	MediumtextNullField            null.String  `exql:"column:mediumtext_null_field" json:"mediumtext_null_field"`
	TextField                      string       `exql:"column:text_field" json:"text_field"`
	TextNullField                  null.String  `exql:"column:text_null_field" json:"text_null_field"`
	LongtextField                  string       `exql:"column:longtext_field" json:"longtext_field"`
	LongtextNullField              null.String  `exql:"column:longtext_null_field" json:"longtext_null_field"`
	VarcharFiledField              string       `exql:"column:varchar_filed_field" json:"varchar_filed_field"`
	VarcharNullField               null.String  `exql:"column:varchar_null_field" json:"varchar_null_field"`
	CharFiledField                 string       `exql:"column:char_filed_field" json:"char_filed_field"`
	CharFiledNullField             null.String  `exql:"column:char_filed_null_field" json:"char_filed_null_field"`
	DateField                      time.Time    `exql:"column:date_field" json:"date_field"`
	DateNullField                  null.Time    `exql:"column:date_null_field" json:"date_null_field"`
	DatetimeField                  time.Time    `exql:"column:datetime_field" json:"datetime_field"`
	DatetimeNullField              null.Time    `exql:"column:datetime_null_field" json:"datetime_null_field"`
	TimeField                      time.Time    `exql:"column:time_field" json:"time_field"`
	TimeNullField                  null.Time    `exql:"column:time_null_field" json:"time_null_field"`
	TimestampField                 time.Time    `exql:"column:timestamp_field;on;update;CURRENT_TIMESTAMP" json:"timestamp_field"`
	TimestampNullField             time.Time    `exql:"column:timestamp_null_field" json:"timestamp_null_field"`
	TinyblobField                  []byte       `exql:"column:tinyblob_field" json:"tinyblob_field"`
	TinyblobNullField              null.Bytes   `exql:"column:tinyblob_null_field" json:"tinyblob_null_field"`
	MediumblobField                []byte       `exql:"column:mediumblob_field" json:"mediumblob_field"`
	MediumblobNullField            null.Bytes   `exql:"column:mediumblob_null_field" json:"mediumblob_null_field"`
	BlobField                      []byte       `exql:"column:blob_field" json:"blob_field"`
	BlobNullField                  null.Bytes   `exql:"column:blob_null_field" json:"blob_null_field"`
	LongblobField                  []byte       `exql:"column:longblob_field" json:"longblob_field"`
	LongblobNullField              null.Bytes   `exql:"column:longblob_null_field" json:"longblob_null_field"`
}

type fieldsExt struct {
}

var FieldsExt = &fieldsExt{}

func (f *fieldsExt) TableName() string {
	return "fields"
}
