// This file is generated by exql. DO NOT edit.
package model



type GroupUsers struct {
		Id int64 `exql:"column:id;type:int(11);primary;not null;auto_increment" json:"id"`
		UserId int64 `exql:"column:user_id;type:int(11);not null" json:"user_id"`
		GroupId int64 `exql:"column:group_id;type:int(11);not null" json:"group_id"`
}

func (g GroupUsers) TableName() string {
	return GroupUsersTableName
}

type UpdateGroupUsers struct {
		Id *int64 `exql:"column:id;type:int(11);primary;not null;auto_increment" json:"id"`
		UserId *int64 `exql:"column:user_id;type:int(11);not null" json:"user_id"`
		GroupId *int64 `exql:"column:group_id;type:int(11);not null" json:"group_id"`
}

func (g UpdateGroupUsers) UpdateTableName() string {
	return GroupUsersTableName
}

const GroupUsersTableName = "group_users"

