// This file is generated by exql. DO NOT edit.
package model

type Groups struct {
	Id   int64  `exql:"column:id;type:int(11);primary;not null;auto_increment" json:"id"`
	Name string `exql:"column:name;type:varchar(255);not null" json:"name"`
}

func (g Groups) TableName() string {
	return GroupsTableName
}

type UpdateGroups struct {
	Id   *int64  `exql:"column:id;type:int(11);primary;not null;auto_increment" json:"id"`
	Name *string `exql:"column:name;type:varchar(255);not null" json:"name"`
}

func (g UpdateGroups) UpdateTableName() string {
	return GroupsTableName
}

const GroupsTableName = "groups"
