// This file is generated by exql. DO NOT edit.
package model

type UserGroups struct {
	Id   int64  `exql:"column:id;type:int(11);primary;not null;auto_increment" json:"id"`
	Name string `exql:"column:name;type:varchar(255);not null" json:"name"`
}

func (u *UserGroups) TableName() string {
	return "user_groups"
}

type userGroupsTable struct {
}

var UserGroupsTable = &userGroupsTable{}

func (u *userGroupsTable) Name() string {
	return "user_groups"
}
