// This file is generated by exql. DO NOT edit.
package model

import "github.com/volatiletech/null"

type Users struct {
	Id        int64       `exql:"column:id;type:int(11);primary;not null;auto_increment" json:"id"`
	FirstName null.String `exql:"column:first_name;type:varchar(255)" json:"first_name"`
	LastName  null.String `exql:"column:last_name;type:varchar(255)" json:"last_name"`
}

func (u Users) TableName() string {
	return UsersTableName
}

type UpdateUsers struct {
	Id        *int64       `exql:"column:id;type:int(11);primary;not null;auto_increment" json:"id"`
	FirstName *null.String `exql:"column:first_name;type:varchar(255)" json:"first_name"`
	LastName  *null.String `exql:"column:last_name;type:varchar(255)" json:"last_name"`
}

func (u UpdateUsers) UpdateTableName() string {
	return UsersTableName
}

const UsersTableName = "users"
