// This file is generated by exql. DO NOT edit.
package model

import "github.com/volatiletech/null"

type Users struct {
		Id int `exql:"column:id;primary;auto_increment" json:"id"`
		FirstName null.String `exql:"column:first_name" json:"first_name"`
		LastName null.String `exql:"column:last_name" json:"last_name"`
}

type usersExt struct {
}

var UsersExt = &usersExt{}

func (u *usersExt) TableName() string {
	return "users"
}