package main

import "github.com/volatiletech/null"

// Model definition. Basically it should be generated by exql.Generator()
type User struct {
	// Primary key should be:
	//	- the first column in table
	//  - int/bigint type in MySQL.
	//  - declared as auto_increment. It will be excluded for insertion query
	Id int64 `exql:"column:id;primary;not null;auto_increment"`
	// Non-null field
	Name string `exql:"column:name;not null"`
	// Nullable field
	Bio null.String `exql:"column:bio"`
}
