version: "3.7"
services:
  mysql:
    container_name: exql_mysql
    image: mysql:5.7
    ports:
      - 13326:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: exql
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
  mysql8:
    container_name: exql_mysql8
    image: mysql:8
    ports:
      - 13327:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: exql
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
