version: "3.7"
services:
  mysql:
    container_name: exql_mysql
    image: mysql:5.6
    ports:
      - 3326:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: exql
    volumes:
      - ./schema:/docker-entrypoint-initdb.d