package migrate

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"
)

// Migrator applies migrations to a database.
type Migrator interface {
	// Up applies all migrations newer than the current version in order.
	Up(ctx context.Context) error
	// Down reverts all applied migrations in reverse order back to the
	// initial state. It is destructive and intended for rebuilding local
	// environments.
	Down(ctx context.Context) error
	// Drop drops all base tables in the current database, including
	// schema_migrations. It is destructive and intended for rebuilding
	// local environments.
	Drop(ctx context.Context) error
	// Version returns the current migration version and the dirty flag.
	// It returns version = -1 if no migration has been applied.
	Version(ctx context.Context) (version int64, dirty bool, err error)
}

// Options is options for New.
type Options struct {
	// @default "exql-migrate:" + current database name
	// Session lock name passed to GET_LOCK to serialize concurrent migrators.
	LockName string
	// @default 10s
	// Timeout for acquiring the session lock.
	LockTimeout time.Duration
	// Called with a progress message for each applied/reverted migration.
	// No output if nil.
	Log func(msg string)
}

type migrator struct {
	db         *sql.DB
	migrations []*Migration
	opts       Options
}

var _ Migrator = (*migrator)(nil)

// New makes a Migrator that applies migrations to db.
// Migrations must be sorted by version in ascending order, as returned
// by Load. opts can be nil.
//
// NOTE: Each migration file is executed as a single Exec call. If your
// migration files contain multiple statements, the connection must be
// opened with multiStatements=true.
func New(db *sql.DB, migrations []*Migration, opts *Options) Migrator {
	m := &migrator{db: db, migrations: migrations}
	if opts != nil {
		m.opts = *opts
	}
	if m.opts.LockTimeout == 0 {
		m.opts.LockTimeout = 10 * time.Second
	}
	return m
}

func (m *migrator) logf(format string, args ...any) {
	if m.opts.Log != nil {
		m.opts.Log(fmt.Sprintf(format, args...))
	}
}

// withLock runs f on a single connection holding the session lock.
// GET_LOCK is a session-scoped lock, so every operation must run on the
// same connection that acquired it.
func (m *migrator) withLock(ctx context.Context, f func(conn *sql.Conn) error) error {
	conn, err := m.db.Conn(ctx)
	if err != nil {
		return err
	}
	defer conn.Close()

	lockName := m.opts.LockName
	if lockName == "" {
		var database sql.NullString
		if err := conn.QueryRowContext(ctx, "SELECT DATABASE()").Scan(&database); err != nil {
			return err
		}
		lockName = "exql-migrate:" + database.String
	}

	var acquired sql.NullInt64
	if err := conn.QueryRowContext(ctx, "SELECT GET_LOCK(?, ?)", lockName, int(m.opts.LockTimeout.Seconds())).Scan(&acquired); err != nil {
		return err
	}
	if !acquired.Valid || acquired.Int64 != 1 {
		return fmt.Errorf("failed to acquire lock %q: another migration may be running", lockName)
	}
	defer func() { _, _ = conn.ExecContext(ctx, "SELECT RELEASE_LOCK(?)", lockName) }()

	return f(conn)
}

// execStmt runs a migration statement. A blank statement (e.g. a file
// just generated by Create) is a no-op, same as golang-migrate.
func execStmt(ctx context.Context, conn *sql.Conn, stmt string) error {
	if strings.TrimSpace(stmt) == "" {
		return nil
	}
	_, err := conn.ExecContext(ctx, stmt)
	return err
}

func ensureVersionTable(ctx context.Context, conn *sql.Conn) error {
	_, err := conn.ExecContext(ctx,
		"CREATE TABLE IF NOT EXISTS schema_migrations (version bigint not null primary key, dirty boolean not null)",
	)
	return err
}

func (m *migrator) Up(ctx context.Context) error {
	return m.withLock(ctx, func(conn *sql.Conn) error {
		if err := ensureVersionTable(ctx, conn); err != nil {
			return err
		}

		version, dirty, err := currentVersion(ctx, conn)
		if err != nil {
			return err
		}
		if dirty {
			return fmt.Errorf("database is dirty at version %d: fix the database manually then update schema_migrations", version)
		}

		for _, mg := range m.migrations {
			if mg.Version <= version {
				continue
			}
			m.logf("applying migration %d_%s", mg.Version, mg.Name)
			if err := setVersion(ctx, conn, mg.Version, true); err != nil {
				return err
			}
			if err := execStmt(ctx, conn, mg.UpStmt); err != nil {
				return fmt.Errorf("migration %d_%s failed (database is now dirty): %w", mg.Version, mg.Name, err)
			}
			if err := setVersion(ctx, conn, mg.Version, false); err != nil {
				return err
			}
		}

		return nil
	})
}

func (m *migrator) Down(ctx context.Context) error {
	return m.withLock(ctx, func(conn *sql.Conn) error {
		if err := ensureVersionTable(ctx, conn); err != nil {
			return err
		}

		version, dirty, err := currentVersion(ctx, conn)
		if err != nil {
			return err
		}
		if dirty {
			return fmt.Errorf("database is dirty at version %d: fix the database manually then update schema_migrations", version)
		}

		var applied []*Migration
		for _, mg := range m.migrations {
			if mg.Version <= version {
				applied = append(applied, mg)
			}
		}
		for i := len(applied) - 1; i >= 0; i-- {
			mg := applied[i]
			if !mg.HasDown {
				return fmt.Errorf("missing down migration for %d_%s", mg.Version, mg.Name)
			}
			// The version after the revert. Reverting the first migration
			// goes back to the initial state (-1).
			target := int64(-1)
			if i > 0 {
				target = applied[i-1].Version
			}
			m.logf("reverting migration %d_%s", mg.Version, mg.Name)
			if err := setVersion(ctx, conn, target, true); err != nil {
				return err
			}
			if err := execStmt(ctx, conn, mg.DownStmt); err != nil {
				return fmt.Errorf("down migration %d_%s failed (database is now dirty): %w", mg.Version, mg.Name, err)
			}
			if err := setVersion(ctx, conn, target, false); err != nil {
				return err
			}
		}

		return nil
	})
}

func (m *migrator) Drop(ctx context.Context) error {
	return m.withLock(ctx, func(conn *sql.Conn) error {
		rows, err := conn.QueryContext(ctx,
			"SELECT table_name FROM information_schema.tables WHERE table_schema = DATABASE() AND table_type = 'BASE TABLE'",
		)
		if err != nil {
			return err
		}
		defer rows.Close()

		var tables []string
		for rows.Next() {
			var t string
			if err := rows.Scan(&t); err != nil {
				return err
			}
			tables = append(tables, "`"+t+"`")
		}
		if err := rows.Err(); err != nil {
			return err
		}
		if len(tables) == 0 {
			return nil
		}

		// SET affects only this session; foreign key checks stay enabled
		// for other connections.
		if _, err := conn.ExecContext(ctx, "SET FOREIGN_KEY_CHECKS = 0"); err != nil {
			return err
		}
		if _, err := conn.ExecContext(ctx, fmt.Sprintf("DROP TABLE %s", strings.Join(tables, ", "))); err != nil {
			return err
		}
		if _, err := conn.ExecContext(ctx, "SET FOREIGN_KEY_CHECKS = 1"); err != nil {
			return err
		}

		return nil
	})
}

func (m *migrator) Version(ctx context.Context) (int64, bool, error) {
	var version int64
	var dirty bool
	err := m.withLock(ctx, func(conn *sql.Conn) error {
		if err := ensureVersionTable(ctx, conn); err != nil {
			return err
		}
		var err error
		version, dirty, err = currentVersion(ctx, conn)
		return err
	})
	return version, dirty, err
}

// currentVersion returns version = -1 if no migration has been applied
// (no row in schema_migrations).
func currentVersion(ctx context.Context, conn *sql.Conn) (version int64, dirty bool, err error) {
	err = conn.QueryRowContext(ctx, "SELECT version, dirty FROM schema_migrations LIMIT 1").Scan(&version, &dirty)
	if err == sql.ErrNoRows {
		return -1, false, nil
	}
	if err != nil {
		return 0, false, err
	}

	return version, dirty, nil
}

func setVersion(ctx context.Context, conn *sql.Conn, version int64, dirty bool) error {
	tx, err := conn.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	// Rollback after a successful Commit is a no-op.
	defer func() { _ = tx.Rollback() }()
	if _, err := tx.ExecContext(ctx, "DELETE FROM schema_migrations"); err != nil {
		return err
	}
	// version = -1 (initial state) is represented by no row, but keep the
	// record if dirty, same as golang-migrate.
	if version >= 0 || dirty {
		if _, err := tx.ExecContext(ctx, "INSERT INTO schema_migrations (version, dirty) VALUES (?, ?)", version, dirty); err != nil {
			return err
		}
	}

	return tx.Commit()
}
